# Generated by Django 5.2.4 on 2025-07-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
